version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssafyhome-spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ssafyhome-mysql:3306/ssafyhome
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - ssafyhome-net

networks:
  ssafyhome-net:
    external: true  # 이미 생성된 네트워크를 사용
